services:
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9932:5432"
    restart: on-failure
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST=postgres

volumes:
  postgres_data: {}
